export const customers = [
  {
    customerId: 'CUST-101',
    companyName: 'ABC Trading LLC',
    contactPerson: 'Ahmed Ali',
    country: 'UAE',
    email: 'ahmed@abctrading.ae',
    phone: '+971 50 123 4567',
    address: 'Office 402, Business Bay, Dubai, UAE',
    taxNumber: 'TRN 100234567890003',
    currency: 'USD',
    paymentTerms: 'Net 30',
    outstandingBalance: 35000,
    status: 'Active'
  },
  {
    customerId: 'CUST-102',
    companyName: 'EuroFoods BV',
    contactPerson: 'Lisa Meyer',
    country: 'Netherlands',
    email: 'lisa@eurofoods.nl',
    phone: '+31 20 555 4321',
    address: 'Keizersgracht 421, Amsterdam, Netherlands',
    taxNumber: 'NL884210954B01',
    currency: 'EUR',
    paymentTerms: 'Advance',
    outstandingBalance: 0,
    status: 'Active'
  },
  {
    customerId: 'CUST-103',
    companyName: 'Apex Imports',
    contactPerson: 'Tom Reed',
    country: 'USA',
    email: 'tom@apeximports.us',
    phone: '+1 929 555 0101',
    address: '500 7th Ave, New York, NY 10018, USA',
    taxNumber: 'US123456789',
    currency: 'USD',
    paymentTerms: '30% Adv + 70% B/L',
    outstandingBalance: 0,
    status: 'Active'
  },
  {
    customerId: 'CUST-104',
    companyName: 'Tokyo Trading',
    contactPerson: 'Kenji Sato',
    country: 'Japan',
    email: 'kenji@tokyotrading.jp',
    phone: '+81 3 5555 0123',
    address: '1-1-2 Marunouchi, Chiyoda-ku, Tokyo, Japan',
    taxNumber: 'JP9876543210123',
    currency: 'USD',
    paymentTerms: 'Net 30',
    outstandingBalance: 12500,
    status: 'Active'
  }
];

export const products = [
  {
    sku: 'PRD-01',
    name: 'Basmati Rice 1121',
    icon: '🌾',
    description: 'Premium long grain export quality',
    hsCode: '1006.30.20',
    unit: 'MT',
    price: 950.00,
    purchasePrice: 780.00,
    countryOfOrigin: 'India',
    stock: 120,
    availableStock: '120 MT',
    minStock: 20,
    status: 'Active',
    category: 'Agricultural Products'
  },
  {
    sku: 'PRD-02',
    name: 'Cotton Yarn 30s',
    icon: '🧶',
    description: 'Combed ring spun 100% cotton yarn',
    hsCode: '5205.12.00',
    unit: 'KG',
    price: 3.40,
    purchasePrice: 2.70,
    countryOfOrigin: 'India',
    stock: 4500,
    availableStock: '4,500 KG',
    minStock: 500,
    status: 'Active',
    category: 'Textiles'
  },
  {
    sku: 'PRD-03',
    name: 'Refined Soybean Oil',
    icon: '🫒',
    description: 'Deodorized food grade cooking oil',
    hsCode: '1507.90.10',
    unit: 'MT',
    price: 850.00,
    purchasePrice: 710.00,
    countryOfOrigin: 'India',
    stock: 18,
    availableStock: '18 MT',
    minStock: 30,
    status: 'Active',
    category: 'Food & Beverages'
  }
];

export const sales = [
  {
    type: 'Sales Order',
    enquiryNo: 'ENQ-308',
    quotationNo: 'QT-204',
    orderNo: 'SO-1024',
    customer: 'ABC Trading LLC',
    customerId: 'CUST-101',
    contactPerson: 'Ahmed Ali',
    email: 'ahmed@abctrading.ae',
    phone: '+971 50 123 4567',
    origin: 'Nhava Sheva Port, Mumbai, India',
    destination: 'Dubai, UAE',
    currency: 'USD',
    incoterm: 'FOB',
    freight: 2500,
    paymentTerms: 'Net 30',
    validity: '30 Days',
    notes: 'Standard seaworthy export packaging.',
    products: [
      {
        name: 'Product A',
        sku: 'PRD-01',
        hsCode: '1006.30.20',
        unit: 'units',
        quantity: 5000,
        unitPrice: 10.00,
        total: 50000
      }
    ],
    totalAmount: 50000,
    advanceReceived: 15000,
    balanceDue: 35000,
    status: 'Confirmed',
    createdAt: new Date('2026-10-02T10:00:00Z')
  },
  {
    type: 'Sales Order',
    enquiryNo: 'ENQ-309',
    quotationNo: 'QT-205',
    orderNo: 'SO-1025',
    customer: 'Apex Imports',
    customerId: 'CUST-103',
    contactPerson: 'Tom Reed',
    email: 'tom@apeximports.us',
    phone: '+1 929 555 0101',
    origin: 'Nhava Sheva Port, Mumbai, India',
    destination: 'New York, USA',
    currency: 'USD',
    incoterm: 'CIF',
    freight: 3000,
    paymentTerms: '30% Adv + 70% B/L',
    validity: '30 Days',
    notes: 'Combed ring spun 100% cotton yarn in export cartons.',
    products: [
      {
        name: 'Cotton Yarn 30s',
        sku: 'PRD-02',
        hsCode: '5205.12.00',
        unit: 'KG',
        quantity: 2000,
        unitPrice: 14.00,
        total: 28000
      }
    ],
    totalAmount: 28000,
    advanceReceived: 28000,
    balanceDue: 0,
    status: 'Ready to Ship',
    createdAt: new Date('2026-10-01T14:30:00Z')
  },
  {
    type: 'Sales Order',
    enquiryNo: 'ENQ-307',
    quotationNo: 'QT-206',
    orderNo: 'SO-1026',
    customer: 'Tokyo Trading',
    customerId: 'CUST-104',
    contactPerson: 'Kenji Sato',
    email: 'kenji@tokyotrading.jp',
    phone: '+81 3 5555 0123',
    origin: 'Chennai Port, India',
    destination: 'Yokohama, Japan',
    currency: 'USD',
    incoterm: 'CFR',
    freight: 1500,
    paymentTerms: 'Net 30',
    validity: '30 Days',
    notes: 'Deodorized food grade cooking oil.',
    products: [
      {
        name: 'Refined Soybean Oil',
        sku: 'PRD-03',
        hsCode: '1507.90.10',
        unit: 'KG',
        quantity: 900,
        unitPrice: 13.88,
        total: 12500
      }
    ],
    totalAmount: 12500,
    advanceReceived: 0,
    balanceDue: 12500,
    status: 'Preparing',
    createdAt: new Date('2026-09-28T09:15:00Z')
  },
  {
    type: 'Quotation',
    quotationNo: 'QT-204',
    enquiryNo: 'ENQ-308',
    customer: 'ABC Trading',
    customerId: 'CUST-101',
    contactPerson: 'Ahmed Ali',
    email: 'ahmed@abctrading.ae',
    phone: '+971 50 123 4567',
    destination: 'Dubai, UAE',
    currency: 'USD',
    incoterm: 'FOB',
    validity: 'Oct 15, 2026',
    totalAmount: 50000,
    status: 'Accepted',
    orderNo: 'SO-1024',
    products: [
      {
        name: 'Product A',
        quantity: 5000,
        unit: 'units',
        unitPrice: 10.00,
        total: 50000
      }
    ]
  },
  {
    type: 'Quotation',
    quotationNo: 'QT-205',
    enquiryNo: 'ENQ-309',
    customer: 'Apex Imports',
    customerId: 'CUST-103',
    contactPerson: 'Tom Reed',
    email: 'tom@apeximports.us',
    destination: 'New York, USA',
    currency: 'USD',
    incoterm: 'CIF',
    validity: 'Oct 20, 2026',
    totalAmount: 28000,
    status: 'Draft',
    products: [
      {
        name: 'Cotton Yarn 30s',
        quantity: 2000,
        unit: 'units',
        unitPrice: 14.00,
        total: 28000
      }
    ]
  },
  {
    type: 'Quotation',
    quotationNo: 'QT-206',
    enquiryNo: 'ENQ-307',
    customer: 'Tokyo Trading',
    customerId: 'CUST-104',
    contactPerson: 'Kenji Sato',
    email: 'kenji@tokyotrading.jp',
    destination: 'Yokohama, Japan',
    currency: 'USD',
    incoterm: 'CFR',
    validity: 'Oct 28, 2026',
    totalAmount: 12500,
    status: 'Sent',
    products: [
      {
        name: 'Refined Soybean Oil',
        quantity: 900,
        unit: 'KG',
        unitPrice: 13.88,
        total: 12500
      }
    ]
  },
  {
    type: 'Enquiry',
    enquiryNo: 'ENQ-311',
    customer: 'EuroFoods BV',
    customerId: 'CUST-102',
    destination: 'Rotterdam, Netherlands',
    currency: 'USD',
    totalAmount: 57000,
    status: 'New',
    createdAt: new Date('2026-09-26T10:00:00Z'),
    products: [
      {
        name: 'Basmati Rice 1121',
        quantity: 60,
        unit: 'MT',
        unitPrice: 950,
        total: 57000
      }
    ]
  },
  {
    type: 'Enquiry',
    enquiryNo: 'ENQ-310',
    customer: 'Apex Imports',
    customerId: 'CUST-103',
    destination: 'New York, USA',
    currency: 'USD',
    totalAmount: 6800,
    status: 'Quoted',
    createdAt: new Date('2026-09-24T11:00:00Z'),
    products: [
      {
        name: 'Cotton Yarn 30s',
        quantity: 2000,
        unit: 'KG',
        unitPrice: 3.40,
        total: 6800
      }
    ]
  }
];



export const initialQuotations = [
  {
    quotationNo: 'QT-204',
    quotationDate: '2026-09-15',
    validUntil: 'Oct 15, 2026',
    customer: 'ABC Trading',
    companyName: 'ABC Trading LLC',
    contactPerson: 'Ahmed Ali',
    email: 'ahmed@abctrading.ae',
    phone: '+971 50 123 4567',
    address: 'Office 402, Business Bay, Dubai, UAE',
    destination: 'Dubai, UAE',
    origin: 'Nhava Sheva Port, Mumbai, India',
    currency: 'USD',
    items: [
      {
        name: 'Product A',
        description: 'Standard Export Consignment',
        quantity: 5000,
        unit: 'units',
        unitPrice: 10.00,
        discount: 0,
        discountType: 'percent',
        taxRate: 0,
        taxAmount: 0,
        lineTotal: 50000
      }
    ],
    subtotal: 50000,
    totalDiscount: 0,
    taxableAmount: 50000,
    taxTotal: 0,
    shippingCharges: 0,
    grandTotal: 50000,
    paymentTerms: 'Net 30',
    deliveryTerms: 'FOB Origin Port',
    incoterm: 'FOB',
    notes: 'Standard seaworthy packaging.',
    termsAndConditions: '1. Prices valid until validity date.\n2. Payment terms as agreed.',
    status: 'Accepted',
    orderNo: 'SO-1024',
    enquiryNo: 'ENQ-308'
  },
  {
    quotationNo: 'QT-205',
    quotationDate: '2026-09-20',
    validUntil: 'Oct 20, 2026',
    customer: 'Apex Imports',
    companyName: 'Apex Imports',
    contactPerson: 'Tom Reed',
    email: 'tom@apeximports.us',
    phone: '+1 929 555 0101',
    address: '500 7th Ave, New York, NY 10018, USA',
    destination: 'New York, USA',
    origin: 'Nhava Sheva Port, Mumbai, India',
    currency: 'USD',
    items: [
      {
        name: 'Cotton Yarn 30s',
        description: 'Combed ring spun 100% cotton yarn',
        quantity: 2000,
        unit: 'units',
        unitPrice: 14.00,
        discount: 0,
        discountType: 'percent',
        taxRate: 0,
        taxAmount: 0,
        lineTotal: 28000
      }
    ],
    subtotal: 28000,
    totalDiscount: 0,
    taxableAmount: 28000,
    taxTotal: 0,
    shippingCharges: 0,
    grandTotal: 28000,
    paymentTerms: '30% Adv + 70% B/L',
    deliveryTerms: 'CIF Destination Port',
    incoterm: 'CIF',
    notes: 'Export standard cartons.',
    termsAndConditions: '1. Prices valid for 30 days.',
    status: 'Draft',
    enquiryNo: 'ENQ-309'
  },
  {
    quotationNo: 'QT-206',
    quotationDate: '2026-09-28',
    validUntil: 'Oct 28, 2026',
    customer: 'Tokyo Trading',
    companyName: 'Tokyo Trading',
    contactPerson: 'Kenji Sato',
    email: 'kenji@tokyotrading.jp',
    phone: '+81 3 5555 0123',
    address: '1-1-2 Marunouchi, Chiyoda-ku, Tokyo, Japan',
    destination: 'Yokohama, Japan',
    origin: 'Chennai Port, India',
    currency: 'USD',
    items: [
      {
        name: 'Refined Soybean Oil',
        description: 'Deodorized food grade cooking oil',
        quantity: 900,
        unit: 'KG',
        unitPrice: 13.88,
        discount: 0,
        discountType: 'percent',
        taxRate: 0,
        taxAmount: 0,
        lineTotal: 12500
      }
    ],
    subtotal: 12500,
    totalDiscount: 0,
    taxableAmount: 12500,
    taxTotal: 0,
    shippingCharges: 0,
    grandTotal: 12500,
    paymentTerms: 'Net 30',
    deliveryTerms: 'CFR Destination Port',
    incoterm: 'CFR',
    notes: 'Food grade export drums.',
    termsAndConditions: '1. Prices valid for 30 days.',
    status: 'Sent',
    enquiryNo: 'ENQ-307'
  },
  {
    quotationNo: 'QUO-2026-0001',
    quotationDate: '2025-04-18',
    validUntil: '2025-05-18',
    customer: 'Global Foods Ltd',
    companyName: 'Global Foods Ltd',
    contactPerson: 'Maria Lopez',
    email: 'maria@globalfoods.de',
    phone: '+49 30 9876 5432',
    address: 'Speicherstadt 14, Hamburg, Germany',
    destination: 'Hamburg, Germany',
    origin: 'Cochin Port, India',
    currency: 'EUR',
    items: [
      {
        name: 'Frozen Shrimps',
        description: 'Vannamei 1kg pack, deep frozen, export grade',
        quantity: 3400,
        unit: 'KG',
        unitPrice: 7.50,
        discount: 2,
        discountType: 'percent',
        taxRate: 0,
        taxAmount: 0,
        lineTotal: 24990
      }
    ],
    subtotal: 25500,
    totalDiscount: 510,
    taxableAmount: 24990,
    taxTotal: 0,
    shippingCharges: 2400,
    grandTotal: 27390,
    paymentTerms: 'Net 30',
    deliveryTerms: 'FOB Cochin Port',
    incoterm: 'FOB',
    notes: 'Deep frozen seafood with temperature loggers installed in container.',
    termsAndConditions: '1. Prices valid for 30 days.\n2. Payment within 30 days of bill of lading.\n3. Quality inspection certificate by SGS provided.',
    status: 'Sent',
    enquiryNo: 'ENQ-1002'
  },
  {
    quotationNo: 'QUO-2026-0002',
    quotationDate: '2025-04-12',
    validUntil: '2025-05-12',
    customer: 'Alpine Co.',
    companyName: 'Alpine Co.',
    contactPerson: 'Robert Wilson',
    email: 'robert@alpine.nl',
    phone: '+31 20 123 4567',
    address: 'Wilhelminakade 953, Rotterdam, Netherlands',
    destination: 'Rotterdam, Netherlands',
    origin: 'Kolkata Port, India',
    currency: 'EUR',
    items: [
      {
        name: 'Organic Honey',
        description: 'Natural pure wild forest honey in 500g glass jars',
        quantity: 3500,
        unit: 'KG',
        unitPrice: 8.50,
        discount: 0,
        discountType: 'percent',
        taxRate: 5,
        taxAmount: 1487.50,
        lineTotal: 31237.50
      }
    ],
    subtotal: 29750,
    totalDiscount: 0,
    taxableAmount: 29750,
    taxTotal: 1487.50,
    shippingCharges: 2800,
    grandTotal: 34037.50,
    paymentTerms: 'Net 45',
    deliveryTerms: 'CFR Rotterdam Port',
    incoterm: 'CFR',
    notes: 'Laboratory purity certificate and batch test reports attached.',
    termsAndConditions: '1. Goods dispatch within 10 days of LC confirmation.\n2. Moisture content verified below 18%.',
    status: 'Draft',
    enquiryNo: 'ENQ-1005'
  },
  {
    quotationNo: 'QUO-2026-0003',
    quotationDate: '2025-04-10',
    validUntil: '2025-05-10',
    customer: 'ABC Trading LLC',
    companyName: 'ABC Trading LLC',
    contactPerson: 'Ahmed Khan',
    email: 'ahmed@abctrading.ae',
    phone: '+971 50 123 4567',
    address: 'Business Bay, Dubai, UAE',
    destination: 'Dubai, UAE',
    origin: 'Nhava Sheva Port, Mumbai, India',
    currency: 'USD',
    items: [
      {
        name: 'Premium Basmati Rice',
        description: 'Long grain, double polished, 25kg PP bags',
        quantity: 80,
        unit: 'MT',
        unitPrice: 580.00,
        discount: 1000,
        discountType: 'amount',
        taxRate: 0,
        taxAmount: 0,
        lineTotal: 45400
      }
    ],
    subtotal: 46400,
    totalDiscount: 1000,
    taxableAmount: 45400,
    taxTotal: 0,
    shippingCharges: 3600,
    grandTotal: 49000,
    paymentTerms: '30% Advance, 70% against BL',
    deliveryTerms: 'CIF Jebel Ali Port, Dubai',
    incoterm: 'CIF',
    notes: 'Seaworthy container packaging with desiccant bags installed.',
    termsAndConditions: '1. 30% advance on confirmation, balance against shipping documents.\n2. Shipment ready in 15 days.',
    status: 'Accepted',
    enquiryNo: 'ENQ-1001',
    orderNo: 'SO-1024'
  },
  {
    quotationNo: 'QUO-2026-0004',
    quotationDate: '2025-04-05',
    validUntil: '2025-05-05',
    customer: 'Top Imports Ltd',
    companyName: 'Top Imports Ltd',
    contactPerson: 'Chen Wei',
    email: 'chen@topimports.cn',
    phone: '+86 10 8765 4321',
    address: 'Nanshan District, Shenzhen, China',
    destination: 'Tokyo, Japan',
    origin: 'Chennai Port, India',
    currency: 'USD',
    items: [
      {
        name: 'Leather Shoes',
        description: "Men's casual leather shoes, boxed & master carton packing",
        quantity: 3200,
        unit: 'PAIR',
        unitPrice: 18.00,
        discount: 5,
        discountType: 'percent',
        taxRate: 0,
        taxAmount: 0,
        lineTotal: 54720
      }
    ],
    subtotal: 57600,
    totalDiscount: 2880,
    taxableAmount: 54720,
    taxTotal: 0,
    shippingCharges: 3000,
    grandTotal: 57720,
    paymentTerms: 'Net 30',
    deliveryTerms: 'FOB Chennai Port',
    incoterm: 'FOB',
    notes: 'Compliant with international REACH footwear export regulations.',
    termsAndConditions: '1. Full inspection report by buyer agent prior to stuffing.',
    status: 'Sent',
    enquiryNo: 'ENQ-1006'
  },
  {
    quotationNo: 'QUO-2026-0005',
    quotationDate: '2025-03-20',
    validUntil: '2025-04-20',
    customer: 'Sunrise Importers',
    companyName: 'Sunrise Importers',
    contactPerson: 'David Smith',
    email: 'david@sunrise.sg',
    phone: '+65 9123 4567',
    address: 'Marina Bay Financial Centre, Singapore',
    destination: 'Singapore',
    origin: 'Chennai Port, India',
    currency: 'USD',
    items: [
      {
        name: 'Textile Fabric (Cotton)',
        description: '100% combed cotton, 150cm width',
        quantity: 2500,
        unit: 'ROLL',
        unitPrice: 4.20,
        discount: 0,
        discountType: 'percent',
        taxRate: 0,
        taxAmount: 0,
        lineTotal: 10500
      }
    ],
    subtotal: 10500,
    totalDiscount: 0,
    taxableAmount: 10500,
    taxTotal: 0,
    shippingCharges: 1200,
    grandTotal: 11700,
    paymentTerms: 'Net 15',
    deliveryTerms: 'CIF Singapore Port',
    incoterm: 'CIF',
    notes: 'Rolls wrapped in moisture proof polythene with barcode labeling.',
    termsAndConditions: 'Standard international fabric export conditions.',
    status: 'Expired',
    enquiryNo: 'ENQ-1003'
  },
  {
    quotationNo: 'QUO-2026-0006',
    quotationDate: '2025-04-02',
    validUntil: '2025-05-02',
    customer: 'Oceanic Trading',
    companyName: 'Oceanic Trading',
    contactPerson: 'Lisa Brown',
    email: 'lisa@oceanicusa.com',
    phone: '+1 929 555 0101',
    address: 'Fifth Ave, New York, NY 10001, USA',
    destination: 'Los Angeles, USA',
    origin: 'Mundra Port, Gujarat, India',
    currency: 'USD',
    items: [
      {
        name: 'Wooden Furniture',
        description: 'Office executive tables, solid wood knocked down packaging',
        quantity: 600,
        unit: 'PC',
        unitPrice: 120.00,
        discount: 0,
        discountType: 'percent',
        taxRate: 0,
        taxAmount: 0,
        lineTotal: 72000
      }
    ],
    subtotal: 72000,
    totalDiscount: 0,
    taxableAmount: 72000,
    taxTotal: 0,
    shippingCharges: 4000,
    grandTotal: 76000,
    paymentTerms: 'Net 30',
    deliveryTerms: 'CIF Long Beach Port, USA',
    incoterm: 'CIF',
    notes: 'ISPM 15 fumigation certified wooden crates.',
    termsAndConditions: '1. Net 30 from BL date. 2. Ocean insurance included.',
    status: 'Accepted',
    enquiryNo: 'ENQ-1004',
    orderNo: 'SO-1028'
  }
];

